### ISSUE TITLE
... You should disable react-transform-hmr in production ...

### ISSUE THREAD

**Issue by mykhailo-riabokon** [gaearon/react-transform-hmr#11] opened 2015-09-22 14:36 UTC
I get this error message then I was trying start `webpack-hot-middleware`.

The main reason is that I imported routes (even if I will not use them) in `server.js` file. And one more interesting thing is, if you rename `render` method, everything will works.

I have created an example of this problem based on redux counter example.
https://github.com/mikhail-riabokon/redux-counter

**Comment by gaearon** [comment] 2015-09-23 10:12
This appears to be a duplicate of #5. Please read the instructions for server rendering there.

**Closed as completed by gaearon** 2015-09-23 10:12 UTC
