### ISSUE TITLE
Migrating from webpack-hmr, Error: locals[0] does not appear to be a `module`

### ISSUE THREAD

**Issue by tomatau** [gaearon/react-transform-hmr#8] opened 2015-09-21 10:08 UTC
When migrating from a working implementation with `react-transform-webpack-hmr` to `react-transform-hmr` I get the following error:

```
Error: locals[0] does not appear to be a `module` object with Hot Module replacement API enabled. You should disable react-transform-hmr in production by using `env` section in Babel configuration. See the example in README: https://github.com/gaearon/react-transform-hmr
```

Here is the .babelrc file I'm using:

``` json
{
  "stage": "0",
  "env": {
    "production": {
      "plugins": [
        "react-require",
        "dead-code-elimination"
      ],
    },
    "development": {
      "plugins": [
        "react-transform",
        "react-require"
      ],
      "extra": {
        "react-transform": [{
          "target": "react-transform-hmr", // changed from react-transform-webpack-hmr
          "imports": ["react"],
          "locals": ["module"]
        }, {
          "target": "react-transform-catch-errors",
          "imports": ["react", "redbox-react"]
        }]
      }
    }
  }
}
```

**Comment by gaearon** [comment] 2015-09-21 13:30
Closing as a duplicate of https://github.com/gaearon/react-transform-hmr/issues/5. This just means that for whatever reason you don't really have HMR enabled. Maybe you're using the same Babel configuration on server and client (you shouldn't), or maybe you don't have hot module replacement enabled in Webpack config.

**Closed as completed by gaearon** 2015-09-21 13:30 UTC

**Comment by tomatau** [comment] 2015-09-25 21:33
It was the server HMR, disabling made it work.. although would be nice to use the same .babelrc for the whole universal project in a convenient manner.

**Comment by gaearon** [comment] 2015-09-25 21:51
I agree but you probably wouldn't want to use other transforms on the server either.
Too easy to get unintended memory leaks and weird behavior.

**Comment by tomatau** [comment] 2015-09-25 22:01
Hmmm - I've been using some:

```
    "react-require",
    "babel-root-import"
```

What are your experiences with the memory leaks and weird behaviour?

**Comment by gaearon** [comment] 2015-09-25 22:03
Sorry, I didn't mean Babel plugins.

I meant that you probably wouldn't want to use `react-transform` or any its friends (`react-transform-hmr`, `react-transform-catch-errors`, etc) on the server.

**Comment by hiddaorear** [comment] 2016-04-14 09:41
Hi,  try this:
webpack.config.js:
devServer: {
    historyApiFallback: true,
    inline: true,
    hot: true,
    progress: true
  }
and package.json:
"scripts": {
    "dev": "webpack-dev-server --progress --hot --profile --colors"
    }

hot is the key.

**Comment by gaearon** [comment] 2016-04-18 14:08
None of this should matter in React Hot Loader 3.
I know React Transform has been a configuration hell; hopefully, this should be solved.
See https://github.com/gaearon/react-hot-boilerplate/pull/61 if you’d like to try it!

**Comment by miniMofish** [comment] 2017-04-12 07:52
@hiddaorear 亲，开发环境编译没有这个错，线上环境编译时有，这又是什么情况？
