### ISSUE TITLE
TypeError: Function.prototype.toString called on incompatible object

### ISSUE THREAD

**Issue by halversondm** [gaearon/react-transform-hmr#73] opened 2016-04-04 21:07 UTC
I'm getting this error on version 1.0.4: `TypeError: Function.prototype.toString called on incompatible object` using Firefox 38.2.0 ESR.  The error prevents the page from loading fully.  The error points to some lodash code for isNative module.  It appeared that a Promise object was passed into the method from the call trace that I did.  

When I back down to 1.0.3 version, the issue is not presented.

**Comment by gaearon** [comment] 2016-04-18 13:33
This is https://github.com/lodash/lodash/issues/2185 and was fixed in https://github.com/lodash/lodash/commit/f953d34c7b422aeb09fa4427932692e045ef18ad and Lodash 4.8.
Newer installs should work fine.

**Closed as completed by gaearon** 2016-04-18 13:33 UTC

**Comment by Robinnnnn** [comment] 2016-05-11 13:51
I'm continuing to get this [bizarre FF error](https://github.com/zloirock/core-js/issues/195) despite improving to Lodash v4.12

**Comment by gaearon** [comment] 2016-05-13 13:37
@Robinnnnn Please provide a project reproducing the issue.

**Comment by Robinnnnn** [comment] 2016-05-13 14:21
@gaearon sorry I didn't provide an update. Turns out it was an issue with an older version of the `async` module. Updated it and the error went away.
